### ISSUE TITLE
Typescript source maps

### ISSUE THREAD

**Issue by joemaidman** [jagreehal/typescript-react-redux-jest-card-game#2]
Hey, @jagreehal thanks for this example with next and typescript. Did you manage to get tsx/ts files source mapped in chrome? I can't seem to get them to show, only the transpiled js files.
![screen shot 2018-02-05 at 17 24 26](https://user-images.githubusercontent.com/2493151/35819083-92b4867c-0a99-11e8-81c6-c93352385697.png)

**Comment by jagreehal** [comment]
It should be possible soon now this is merged https://github.com/zeit/next.js/pull/3578

**Comment by jagreehal** [comment]
Works great in Next 5!
